name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    name: Build (${{ matrix.os }}) 
    runs-on: ${{ matrix.os }}
    
    strategy: 
      fail-fast: false 
      matrix: 
        os: 
          - ubuntu-latest 
          - macos-latest 
          - windows-latest

    steps:
    - uses: actions/checkout@v7

    - name: Set up Go
      uses: actions/setup-go@v7
      with:
        go-version-file: 'go.mod'

    - name: Set up Java
      uses: actions/setup-java@v6
      with:
        distribution: temurin
        java-version: '21'

    - name: Install ANTLR tool
      run: pip install antlr4-tools

    - name: Generate parser
      run: go generate ./...

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

  lint: 
    runs-on: ubuntu-latest 
    steps: 
    - uses: actions/checkout@v7 
    
    - name: Set up Go 
      uses: actions/setup-go@v7 
      with: 
        go-version-file: 'go.mod' 
        
    - name: Set up Java
      uses: actions/setup-java@v5
      with:
        distribution: temurin
        java-version: '21'

    - name: Install ANTLR tool
      run: pip install antlr4-tools

    - name: Generate parser
      run: go generate ./...

    - name: Lint 
      uses: golangci/golangci-lint-action@v9